<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <PackageId>Estrelio.AdditionalFluentValidation</PackageId>
        <version>0.0.2</version>
        <authors>TabooSun</authors>
        <TargetFramework>net9.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
        <Description>Contains additional FluentValidation rules</Description>
    </PropertyGroup>

    <PropertyGroup>
        <RestorePackagesWithLockFile>true</RestorePackagesWithLockFile>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="Estrelio.Linter" Version="0.0.2">
            <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
        </PackageReference>
        <PackageReference Include="FluentValidation" Version="11.11.0" />
        <PackageReference Include="libphonenumber-csharp" Version="8.13.52" />
    </ItemGroup>
</Project>
